driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: resource_x509
  run_list:
  - recipe[test::resource_x509]
- name: resource_dhparam
  run_list:
  - recipe[test::resource_dhparam]
- name: upgrade
  run_list:
  - recipe[test::upgrade]
- name: resource_rsa_key
  run_list:
  - recipe[test::resource_rsa_key]
